@echo OFF

SET PROJECT_PATH=%cd%
SET CODE_PATH=%PROJECT_PATH%\grim-code
SET DATA_PATH=%PROJECT_PATH%\grim-data
SET GRIMDAT_PATH=%CODE_PATH%\Tools\GrimDat
SET PYTHONPATH=%CODE_PATH%\bin\python

start cmd